#.streamlit/secrets.toml
OPENAI_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyCGIp3hh3xBkQyw8NUgz_UtTNXU2KOVnLo"
GROK_API_KEY = "xai-Ra17WIikQnhFgT46Q2GXK5s97NugslUi4KyWiVfcEotk9eDdmBn8UIF37U2U4c1LOP1THSGsk7aC2mI6"